# Generated by Django 4.0.3 on 2023-10-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='resume_text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='performance_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
