# Generated by Django 4.0.3 on 2023-10-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_interview_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='resume',
        ),
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
