# Generated by Django 4.2.6 on 2023-10-22 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_interview_company_name_interview_resume_text_and_more"),
        ("core", "0002_session_analysis_result_session_analysis_status_and_more"),
    ]

    operations = []
