# Generated by Django 4.2.6 on 2023-10-22 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_merge_20231022_1039"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysis",
            old_name="interview",
            new_name="session",
        ),
    ]
