# Generated by Django 4.0.3 on 2023-10-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_interview_resume_alter_interview_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='resume',
            field=models.FileField(default='test', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
